CREATE DATABASE IF NOT EXISTS marketplace_db;
CREATE DATABASE IF NOT EXISTS seller_db;

GRANT ALL PRIVILEGES ON marketplace_db.* TO 'demo'@'%';
GRANT ALL PRIVILEGES ON seller_db.* TO 'demo'@'%';
FLUSH PRIVILEGES;
